"""initial tables

Revision ID: adc985064939
Revises: 
Create Date: 2026-06-04 14:30:09.814944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc985064939'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('command', sa.String(length=1024), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('base_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('max_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('next_run_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PERMANENTLY_FAILED', name='status'), nullable=False),
    sa.Column('source', sa.Enum('SCHEDULED', 'MANUAL', name='source'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enqueued_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_run_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PERMANENTLY_FAILED', name='status'), nullable=False),
    sa.Column('to_state', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PERMANENTLY_FAILED', name='status'), nullable=False),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_transitions')
    op.drop_table('job_runs')
    op.drop_table('workers')
    op.drop_table('jobs')
    # ### end Alembic commands ###
